### ISSUE TITLE
Output SpinKube YAML

### ISSUE THREAD

**Issue by itowlson** [itowlson/spin-variables#3]
Generate a YAML file or fragment (I don't know well enough to be clear yet) that sets the appropriate environment variables, which the user can easily edit values into and use in their deployment.  E.g. `spin variables -f ... -o kube >vars.yaml`.

**Comment by technosophos** [comment]
At it's most primitive, it's something like this (plus whatever the secrets/configmap variety is)
```
variables:
  - name: "title" 
    value: "Luxor Demo"
  - name: "about"
    value: "Example of the Luxor platform distributed over 3 working groups"
  - name: "proxy_upstream_repository_host"
    value: "http://luxor-backend.default.svc.cluster.local"
```

I figure that with output like that, one could copy it into the appropriate SpinApp yaml

**Comment by itowlson** [comment]
@technosophos My current stab is:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: spinapp-cfg
data:
  # databaseUrl: http://example.com
---
kind: Secret
apiVersion: v1
metadata:
  name: spinapp-secret
data:
  databasePassword: TO-DO
---
spec:
  variables:
    - name: database_url
      valueFrom:
        configMapKeyRef:
          name: spinapp-cfg
          key: databaseUrl
          optional: true
    - name: database_password
      valueFrom:
        secretKeyRef:
          name: spinapp-secret
          key: databasePassword
          optional: false
```

Do you prefer the name-value form, or should I emit both, or offer them as separate options?
